<?php

    $idioma = array(
        "idioma" => "pt",
        "titulo" => "Projeto Haiti",
        "sub_titulo" => "Sistema de cadastro de currículos",
        "link_cadastro" => "Cadastrar Currículo",
        "ver_curriculos" => "Ver currículos",
        "sobre" => "Sobre o Projeto",
        "contato" => "Contato",
        "login" => "Login",
        "curriculos_cadastrados" => "Curriculos Cadastrados",
        "nome" => "Nome completo",
        "genero" => "Gênero",
        "acao" => "Ações",
        "infos" => "Mais Informações",
        "cad_novo" => "Cadastrar novo Curriculo",
        "dados_pessoais" => "Dados Pessoais",
        "data_nasc" => "Data de Nascimento",
        "escolha" => "Escolha",
        "masculino" => "Masculino",
        "feminino" => "Feminino",
        "outro" => "Outro",
        "est_civil" => "Estado Cívil",
        "solteiro" => "Solteiro (a)",
        "casado" => "Casado (a)",
        "divorciado" => "Divorciado (a)",
        "viuvo" => "Viúvo (a)",
        "pais_origem" => "País de Origem",
        "data_entrada" => "Data de Entrada no Brasil",
        "parentes" => "Grau de Parentesco",
        "conjugue" => "Conjugue",
        "filho" => "Filho",
        "filha" => "Filha",
        "irmao" => "Irmão",
        "irma" => "Irmã",
        "pai" => "Pai",
        "mae" => "Mãe",
        "outro" => "Outro",
        "mora_junto" => "Mora Junto?",
        "sim" => "Sim",
        "nao" => "Não",
        "remover" => "Remover",
        "info_contato" => "Informações de Contato",
        "email" => "Email",
        "telefone" => "Telefone",
        "endereco" => "Endereço",
        "numero" => "Número",
        "bairro" => "Bairro",
        "cep" => "CEP",
        "cidade" => "Cidade",
        "formacao" => "Formação",
        "escolaridade" => "Escolaridade",
        "fundamental" => "Ensino Fundamental",
        "medio" => "Ensino Médio",
        "tecnico" => "Ensino Técnico",
        "superior" => "Ensino Superior",
        "ano_grad" => "Ano de Graduação",
        "instituicao" => "Instituição",
        "pais" => "País",
        "profissao" => "Profissão",
        "descricao" => "Descrição",
        "idiomas" => "Idiomas",
        "pt" => "Português",
        "en" => "Inglês",
        "cr" => "Crioulo",
        "fr" => "Francês",
        "es" => "Espanhol",
        "fluencia" => "Fluência",
        "basico" => "Básico",
        "intermediario" => "Intermediário",
        "fluente" => "Fluente",
        "exp_profissional" => "Experiencia Profissional",
        "empresa" => "Empresa",
        "pais" => "País",
        "inicio" => "Data de Inicio",
        "fim" => "Data de Término",
        "cargo" => "Cargo",
        "funcoes" => "Funções",
        "cont_referencia" => "Contato de Referência",
        "cadastrar" => "Cadastrar",




    );

?>
